### ISSUE TITLE
Does not compile with Swift 2.0

### ISSUE THREAD

**Issue by marcopelegrini** [kfix/MacPin#9]
You will get some error if you try to compile using Swift 2.0. As I am not a Swift programmer I cannot help. :(

modules/Async/Async.swift:208:18: error: '#' has been removed from Swift; double up 'after after' to make the argument label the same as the parameter name
        func background(#after: Double, block: dispatch_block_t) -> Async {
                        ^
                        after
modules/Async/Async.swift:295:24: error: redundant conformance of 'qos_class_t' to protocol 'Equatable'
extension qos_class_t: Equatable {}
                       ^
Darwin.qos_class_t:1:15: note: 'qos_class_t' declares conformance to protocol 'Equatable' here
public struct qos_class_t : RawRepresentable, Equatable {
              ^
modules/Async/Async.swift:291:12: error: value of type 'qos_class_t' has no member 'value'
    return lhs.value ~= rhs.value

**Comment by kfix** [comment]
I'll be targeting Swift 2.1, just haven't done it yet.

**Comment by kfix** [comment]
In the meantime, keep an old copy of Xcode6 around (/Applications/Xcode6.app works) and use `xcode-select` to switch to 6 before `make allapps`

**Comment by marcopelegrini** [comment]
It worked flawlessly, thanks.
Nice tool you have here BTW. Just made a WhatsApp wrapper :) :+1:

**Comment by kfix** [comment]
Wow, cool! Feel free to make a PR for sites/WhatsApp when you're happy with it.

**Comment by kfix** [comment]
Fixed in b5aa107df60c095a1bb56289300e10c6b38542af
